packages:
  - e2e
  - examples/*
  - types/*
  - webapps/*
  - services/*
  - cli/*
  - libs/*

catalog:
  tsx: ^4.21.0
  typescript: ^5.6.3
  esbuild: ^0.27.0
  tslib: ^2.6.3
  "@types/node": ^18.15.3
  vitest: ^4.1.4
  "@vitest/ui": ^4.1.4
  lodash: ^4.18.1
  "@types/lodash": ^4.17.24
  ts-node: ^10.9.2
  react: ^18.3.1
  "react-dom": ^18.3.1
  "@types/react": 18.3.0
  "@types/react-dom": 18.3.1
  eslint: ^9.39.4
  "@eslint/js": ^9.39.2
  tailwindcss: ^3.4.14

onlyBuiltDependencies:
  - "@confluentinc/kafka-javascript"
  - "@firebase/util"
  - "@prisma/client"
  - "@prisma/engines"
  - core-js
  - core-js-pure
  - cpu-features
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - ssh2
  - turbo
  - zstd-napi
