server:
  allowed_domains:
    - '{{APP_TLD}}'
    - 'localhost'
  name: jitsu
  auth: '${env.CLUSTER_ADMIN_TOKEN|env.CONFIGURATOR_ADMIN_TOKEN|demo___please_provide_value_in_production___}'

storage:
  redis:
    host: '${env.REDIS_URL}'
    tls_skip_verify: '${env.TLS_SKIP_VERIFY|false}'

jitsu:
  server_public_url: '${env.JITSU_SERVER_PUBLIC_URL|}'
  base_url: '${env.JITSU_SERVER_URL|}'
  admin_token: '${env.CLUSTER_ADMIN_TOKEN|env.SERVER_ADMIN_TOKEN|demo___please_provide_value_in_production___}'

auth:
  redis:
    host: '${env.REDIS_URL}'
    tls_skip_verify: '${env.TLS_SKIP_VERIFY|false}'

ui:
  base_url: /configurator
