// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3b290fb6DecodeGithubComKsensehqEventnativeHandlers(in *jlexer.Lexer, out *jsConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "key":
			out.Key = string(in.String())
		case "segment_hook":
			out.SegmentHook = bool(in.Bool())
		case "tracking_host":
			out.TrackingHost = string(in.String())
		case "cookie_domain":
			out.CookieDomain = string(in.String())
		case "ga_hook":
			out.GaHook = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b290fb6EncodeGithubComKsensehqEventnativeHandlers(out *jwriter.Writer, in jsConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"segment_hook\":"
		out.RawString(prefix)
		out.Bool(bool(in.SegmentHook))
	}
	{
		const prefix string = ",\"tracking_host\":"
		out.RawString(prefix)
		out.String(string(in.TrackingHost))
	}
	if in.CookieDomain != "" {
		const prefix string = ",\"cookie_domain\":"
		out.RawString(prefix)
		out.String(string(in.CookieDomain))
	}
	{
		const prefix string = ",\"ga_hook\":"
		out.RawString(prefix)
		out.Bool(bool(in.GaHook))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b290fb6EncodeGithubComKsensehqEventnativeHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b290fb6EncodeGithubComKsensehqEventnativeHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b290fb6DecodeGithubComKsensehqEventnativeHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b290fb6DecodeGithubComKsensehqEventnativeHandlers(l, v)
}
func easyjson3b290fb6DecodeGithubComKsensehqEventnativeHandlers1(in *jlexer.Lexer, out *StaticHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b290fb6EncodeGithubComKsensehqEventnativeHandlers1(out *jwriter.Writer, in StaticHandler) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StaticHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b290fb6EncodeGithubComKsensehqEventnativeHandlers1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StaticHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b290fb6EncodeGithubComKsensehqEventnativeHandlers1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StaticHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b290fb6DecodeGithubComKsensehqEventnativeHandlers1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StaticHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b290fb6DecodeGithubComKsensehqEventnativeHandlers1(l, v)
}
