import GithubProvider from "next-auth/providers/github";
import CredentialsProvider from "next-auth/providers/credentials";
import { NextAuthOptions, User } from "next-auth";
import { db } from "./server/db";
import { OIDCProvider, ParseJSONConfigFromEnv } from "./oidc";
import { checkHash, requireDefined } from "juava";
import { ApiError } from "./shared/errors";
import { getServerLog } from "./server/log";
import { withProductAnalytics } from "./server/telemetry";
import { NextApiRequest } from "next";
import { onUserCreated } from "./server/ee";
import { getServerEnv } from "./server/serverEnv";

const crypto = require("crypto");

const log = getServerLog("auth");

const serverEnv = getServerEnv();

export const githubLoginEnabled = !!serverEnv.GITHUB_CLIENT_ID;
export const oidcLoginEnabled = !!serverEnv.AUTH_OIDC_PROVIDER;
export const oidcLoginConfig = ParseJSONConfigFromEnv(serverEnv.AUTH_OIDC_PROVIDER as string);
export const credentialsLoginEnabled =
  serverEnv.ENABLE_CREDENTIALS_LOGIN || !!(serverEnv.SEED_USER_EMAIL && serverEnv.SEED_USER_PASSWORD);

const githubProvider = githubLoginEnabled
  ? GithubProvider({
      clientId: serverEnv.GITHUB_CLIENT_ID as string,
      clientSecret: serverEnv.GITHUB_CLIENT_SECRET as string,
    })
  : undefined;

const oidcProvider = oidcLoginConfig ? OIDCProvider(oidcLoginConfig) : undefined;

const credentialsProvider =
  credentialsLoginEnabled &&
  CredentialsProvider({
    authorize: async function (credentials) {
      if (!credentials) {
        log.atWarn().log(`Failed attempt to login with empty credentials`);
        return null;
      }
      const username = credentials.username;
      if (!username) {
        throw new ApiError("Username is not defined");
      }
      const user = await db.prisma().userProfile.findFirst({ where: { email: username }, include: { password: true } });
      if (!user) {
        log.atDebug().log(`Attempt to login with unknown user: ${username}`);
      } else if (user.password && checkHash(user.password.hash, credentials.password)) {
        log.atDebug().log(`User ${username} logged in successfully with password`);
        return {
          id: user.id,
          externalId: user.externalId,
          email: user.email,
          name: user.name,
        };
      }
      if (!user) {
        log.atWarn().log(`Can't proceed with login, ${username} not found`);
      } else if (!user.password) {
        log.atWarn().log(`Can't proceed with login, ${username} doesn't have a password`);
      } else {
        log.atDebug().log(`Unsuccessful login attempt: user ${username} exists, but password is invalid`);
      }
      return null;
    },
    credentials: {
      username: { label: "Email", type: "text" },
      password: { label: "Password", type: "password" },
    },
  });

export async function getOrCreateUser(opts: {
  externalId: string;
  loginProvider: string;
  name?: string;
  email: string;
  // we only need this for product analytics, so it's optional
  req?: NextApiRequest;
}): Promise<User & { loginProvider: string; externalId: string; admin: boolean | null; mustChangePassword: boolean }> {
  const { externalId, loginProvider, email, name = email } = opts;
  let user = await db.prisma().userProfile.findFirst({
    where: { externalId, loginProvider },
    include: { password: true },
  });
  if (!user) {
    if (serverEnv.DISABLE_SIGNUP) {
      throw new ApiError("Sign up is disabled", { code: "signup-disabled" });
    }
    //first user is admin
    const admin = !(await db.prisma().userProfile.count());
    user = await db.prisma().userProfile.create({
      data: {
        //we need this to be consistent with id generated by .authorize() call
        id: loginProvider === "credentials" ? externalId : undefined,
        email,
        name,
        externalId: externalId,
        loginProvider: loginProvider,
        admin,
      },
      include: {
        password: true,
      },
    });
    await withProductAnalytics(p => p.track("user_created"), {
      user: { email, name, internalId: user.id, externalId, loginProvider },
      req: opts.req,
    });
    await onUserCreated({ email, name });
  } else if (user.name !== name || user.email !== email) {
    await db.prisma().userProfile.update({ where: { id: user.id }, data: { name, email } });
    // Re-fetch to get updated data with password relation
    user = await db.prisma().userProfile.findFirst({
      where: { id: user.id },
      include: { password: true },
    });
    if (!user) {
      throw new ApiError("User not found after update");
    }
  }
  return {
    ...user,
    mustChangePassword: user.password?.changeAtNextLogin ?? false,
  };
}

function generateSecret(base: (string | undefined)[]) {
  const hash = crypto.createHash("sha256");
  hash.update(base.map(s => s || "empty").join(":"));
  const secretKey = hash.digest("hex");
  log.atInfo().log("Using autogenerated JWT key", secretKey);
  return secretKey;
}

export const nextAuthConfig: NextAuthOptions = {
  // Configure one or more authentication providers
  providers: [githubProvider, oidcProvider, credentialsProvider].filter(provider => !!provider) as any,
  pages: {
    error: "/error/auth", // Error code passed in query string as ?error=
    signIn: "/signin", // Displays signin buttons
  },

  secret:
    serverEnv.JWT_SECRET ||
    //if there's no explicit JWT_SECRET, we need to generate a secret based on some values that are unique for an installation
    generateSecret([
      "v2",
      serverEnv.GITHUB_CLIENT_ID,
      serverEnv.GOOGLE_CLIENT_ID,
      serverEnv.DATABASE_URL,
    ]),
  callbacks: {
    jwt: async props => {
      const loginProvider = (props.account?.provider || props.token.loginProvider || "credentials") as string;
      const externalId = requireDefined(props.token.sub, `JWT token .sub is not defined`);
      const email = requireDefined(props.token.email, `JWT token .email is not defined`);
      const user = await getOrCreateUser({
        externalId,
        loginProvider,
        email,
        name: props.token.name || email,
      });
      return {
        internalId: user.id,
        externalId: externalId,
        mustChangePassword: user.mustChangePassword,
        externalUsername: props.profile?.["login"],
        loginProvider: loginProvider,
        ...props.token,
      };
    },
    async session({ session, token }) {
      return {
        ...session,
        mustChangePassword: token.mustChangePassword,
        internalId: token.internalId,
        loginProvider: token.loginProvider,
        externalId: token.externalId,
        externalUsername: token.externalUsername,
      };
    },
  },
};
