export const countries = {
  US: { flag: "🇺🇸", name: "United States" },
  GB: { flag: "🇬🇧", name: "United Kingdom" },
  CA: { flag: "🇨🇦", name: "Canada" },
  DE: { flag: "🇩🇪", name: "Germany" },
  FR: { flag: "🇫🇷", name: "France" },
  IT: { flag: "🇮🇹", name: "Italy" },
  ES: { flag: "🇪🇸", name: "Spain" },
  RU: { flag: "🇷🇺", name: "Russia" },
  CN: { flag: "🇨🇳", name: "China" },
  JP: { flag: "🇯🇵", name: "Japan" },
  IN: { flag: "🇮🇳", name: "India" },
  BR: { flag: "🇧🇷", name: "Brazil" },
  AU: { flag: "🇦🇺", name: "Australia" },
  ZA: { flag: "🇿🇦", name: "South Africa" },
  AR: { flag: "🇦🇷", name: "Argentina" },
  MX: { flag: "🇲🇽", name: "Mexico" },
  NL: { flag: "🇳🇱", name: "Netherlands" },
  SE: { flag: "🇸🇪", name: "Sweden" },
  NO: { flag: "🇳🇴", name: "Norway" },
  FI: { flag: "🇫🇮", name: "Finland" },
  DK: { flag: "🇩🇰", name: "Denmark" },
  PL: { flag: "🇵🇱", name: "Poland" },
  GR: { flag: "🇬🇷", name: "Greece" },
  IE: { flag: "🇮🇪", name: "Ireland" },
  PT: { flag: "🇵🇹", name: "Portugal" },
  BE: { flag: "🇧🇪", name: "Belgium" },
  CH: { flag: "🇨🇭", name: "Switzerland" },
  AT: { flag: "🇦🇹", name: "Austria" },
  TR: { flag: "🇹🇷", name: "Turkey" },
  SA: { flag: "🇸🇦", name: "Saudi Arabia" },
  AE: { flag: "🇦🇪", name: "United Arab Emirates" },
  IL: { flag: "🇮🇱", name: "Israel" },
  EG: { flag: "🇪🇬", name: "Egypt" },
  NG: { flag: "🇳🇬", name: "Nigeria" },
  KE: { flag: "🇰🇪", name: "Kenya" },
  GH: { flag: "🇬🇭", name: "Ghana" },
  TZ: { flag: "🇹🇿", name: "Tanzania" },
  UG: { flag: "🇺🇬", name: "Uganda" },
  ZW: { flag: "🇿🇼", name: "Zimbabwe" },
  MZ: { flag: "🇲🇿", name: "Mozambique" },
  AO: { flag: "🇦🇴", name: "Angola" },
  CM: { flag: "🇨🇲", name: "Cameroon" },
  BJ: { flag: "🇧🇯", name: "Benin" },
  TG: { flag: "🇹🇬", name: "Togo" },
  CI: { flag: "🇨🇮", name: "Ivory Coast" },
  SN: { flag: "🇸🇳", name: "Senegal" },
  ML: { flag: "🇲🇱", name: "Mali" },
  BF: { flag: "🇧🇫", name: "Burkina Faso" },
  NE: { flag: "🇳🇪", name: "Niger" },
  TD: { flag: "🇹🇩", name: "Chad" },
  MR: { flag: "🇲🇷", name: "Mauritania" },
  SD: { flag: "🇸🇩", name: "Sudan" },
  ER: { flag: "🇪🇷", name: "Eritrea" },
  DJ: { flag: "🇩🇯", name: "Djibouti" },
  ET: { flag: "🇪🇹", name: "Ethiopia" },
  SO: { flag: "🇸🇴", name: "Somalia" },
  GM: { flag: "🇬🇲", name: "Gambia" },
  GW: { flag: "🇬🇼", name: "Guinea-Bissau" },
  GN: { flag: "🇬🇳", name: "Guinea" },
  SL: { flag: "🇸🇱", name: "Sierra Leone" },
  LR: { flag: "🇱🇷", name: "Liberia" },
  CF: { flag: "🇨🇫", name: "Central African Republic" },
  GA: { flag: "🇬🇦", name: "Gabon" },
  CG: { flag: "🇨🇬", name: "Congo - Brazzaville" },
  CD: { flag: "🇨🇩", name: "Congo - Kinshasa" },
  IO: { flag: "🇮🇴", name: "British Indian Ocean Territory" },
  AC: { flag: "🇦🇨", name: "Ascension Island" },
  CP: { flag: "🇨🇵", name: "Clipperton Island" },
  EA: { flag: "🇪🇦", name: "Ceuta & Melilla" },
  DG: { flag: "🇩🇬", name: "Diego Garcia" },
  IC: { flag: "🇮🇨", name: "Canary Islands" },
  TA: { flag: "🇹🇦", name: "Tristan da Cunha" },
  HK: { flag: "🇭🇰", name: "Hong Kong" },
  UA: { flag: "🇺🇦", name: "Ukraine" },
  BY: { flag: "🇧🇾", name: "Belarus" },
  MD: { flag: "🇲🇩", name: "Moldova" },
  LV: { flag: "🇱🇻", name: "Latvia" },
  LT: { flag: "🇱🇹", name: "Lithuania" },
  EE: { flag: "🇪🇪", name: "Estonia" },
  GE: { flag: "🇬🇪", name: "Georgia" },
  AM: { flag: "🇦🇲", name: "Armenia" },
  XK: { flag: "🇽🇰", name: "Kosovo" },
  RS: { flag: "🇷🇸", name: "Serbia" },
  ME: { flag: "🇲🇪", name: "Montenegro" },
  MK: { flag: "🇲🇰", name: "North Macedonia" },
  AL: { flag: "🇦🇱", name: "Albania" },
  RO: { flag: "🇷🇴", name: "Romania" },
  BG: { flag: "🇧🇬", name: "Bulgaria" },
  CY: { flag: "🇨🇾", name: "Cyprus" },
  MT: { flag: "🇲🇹", name: "Malta" },
};
